#!/bin/bash
figlet $USER @ $HOSTNAME
echo """
 Marcel Kapfer (mmk2410)
 aka Wilson O'Sullivan

 Programmer, Composer, Blogger

 marcel-kapfer.de / mmk2410.org
 Twitter:    @mmk2410
 GitLab:     /mmk2410
 Google+:    +MarcelMichaelKapfer
"""
