#! /bin/sh

sxhkd &
polybar main &
picom &
~/.fehbg
xmodmap ~/.Xmodmap

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a Emacs state=tiled
