#!/bin/sh

######################################
### Additional X Environment variables
######################################

export QT_QPA_PLATFORMTHEME=qt5ct

##################################
### Adjust for multi-monitor setup
##################################

extern="HDMI-1"
intern="eDP-1"

if xrandr | grep "$extern connected"; then
    xrandr --output "$extern" --auto --primary --left-of "$intern"
fi
